name: Make dev build
on:
  workflow_dispatch:
    inputs:
      buildType:
        description: 'Build Type'
        required: true
        type: choice
        options:
          - release
          - debug
        default: 'release'
      outputFormat:
        description: 'Output format'
        required: true
        type: choice
        options:
          - apk
          - aab
        default: 'apk'
      uploadToDrive:
        description: 'Upload to Drive?'
        required: true
        type: boolean
        default: true
      uploadToFirebase:
        description: 'Upload to Firebase? (If yes and aab, ensure linked to Google Play)'
        required: true
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Validating upload flags
        if: inputs.uploadToDrive == false && inputs.uploadToFirebase == false
        run: |
          echo "uploadToDrive and uploadToFirebase can not both be false"
          exit 1
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'gradle'
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Grant gradlew permissions
        run: chmod +x ./gradlew
      - name: Decode the keystore
        env:
          ENCODED_STRING: ${{ secrets.ENCODED_KEYSTORE }}
        run: |
          TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
          mkdir -p "${TMP_KEYSTORE_FILE_PATH}"
          echo "$ENCODED_STRING" | base64 -di > "${TMP_KEYSTORE_FILE_PATH}/ks.jks"
      - name: Read release notes
        id: readReleaseNotes
        run: |
          {
            echo 'release_notes<<EOF'
            cat RELEASE.md
            echo EOF
          } >> "$GITHUB_OUTPUT"
      - name: Build APK/AAB
        id: buildapk
        run: |
          buildPrefix="assemble"
          outFormat="${{ inputs.outputFormat }}"
          if [ "$outFormat" == 'aab' ]; then buildPrefix="bundle"; fi
          
          buildType="${{ inputs.buildType }}"
          buildTypeCapitalized="$(tr '[:lower:]' '[:upper:]' <<< ${buildType:0:1})${buildType:1}"
          buildCmd="${buildPrefix}Dev${buildTypeCapitalized}"
          
          ./gradlew "$buildCmd"
          
          ext="*.${outFormat}"
          apk_path=$(find $PWD/app/build/outputs/ -type f -name "$ext" | head -n 1)
          apk_size_byte=$(stat -c %s "$apk_path")
          apk_size_mb=$(echo "${apk_size_byte}" | awk '{ $1/=1048576; printf "%.2f", $1 }')
          apk_size="$apk_size_mb MB"
          
          echo "apk_path=$apk_path" >> "$GITHUB_OUTPUT"
          echo "apk_size=$apk_size" >> "$GITHUB_OUTPUT"
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      - name: Upload build to Drive
        id: uploadToDrive
        if: inputs.uploadToDrive
        run: |
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib
          echo '${{ secrets.SERVICE_ACC_KEY_DEV }}' > sa.json
          python - <<'EOF'
          import os
          from google.oauth2 import service_account
          from googleapiclient.discovery import build
          from googleapiclient.http import MediaFileUpload

          creds = service_account.Credentials.from_service_account_file("sa.json", scopes=["https://www.googleapis.com/auth/drive"])
          service = build("drive", "v3", credentials=creds)

          folder_id = '${{ secrets.GG_DRIVE_FOLDER_ID }}'
          file_path = "${{ steps.buildapk.outputs.apk_path }}"
          file_name = os.path.basename(file_path)
          print("Uploading:", file_path)
          
          file_metadata = {"name": file_name, "parents": [folder_id]}
          media = MediaFileUpload(file_path, resumable=True)

          file = service.files().create(body=file_metadata, media_body=media, fields="id, webViewLink", supportsAllDrives=True).execute()
          link = file.get("webViewLink")
          print("Uploaded File ID:", link)
          
          with open(os.environ["GITHUB_OUTPUT"], "a") as fh:
            print(f"fileLink={link}", file=fh)
          EOF
      - name: Upload build to Firebase
        if: inputs.uploadToFirebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID_DEV }}
          serviceCredentialsFileContent: ${{ secrets.SERVICE_ACC_KEY_DEV }}
          groups: ${{ secrets.FIREBASE_TESTER_GROUPS_DEV }}
          releaseNotesFile: RELEASE.md
          file: "${{ steps.buildapk.outputs.apk_path }}"
      - name: Prepare result message
        id: resultMessage
        run: |
          verName=$(grep -oE 'versionName\s*=\s*"[^"]+"' gradle/libs.versions.toml | awk -F '"' '{print $2}')
          verCode=$(grep -oE 'versionCode\s*=\s*"[^"]+"' gradle/libs.versions.toml | awk -F '"' '{print $2}')
          
          uploadToDrive="${{ inputs.uploadToDrive }}"
          uploadToDriveResult="No"
          if [ "$uploadToDrive" == 'true' ]; then uploadToDriveResult="${{ steps.uploadToDrive.outputs.fileLink }}"; fi
          
          uploadToFirebase="${{ inputs.uploadToFirebase }}"
          uploadToFirebaseResult="No"
          if [ "$uploadToFirebase" == 'true' ]; then uploadToFirebaseResult="https://appdistribution.firebase.google.com/testerapps/${{secrets.FIREBASE_APP_ID_DEV}}"; fi
          
          echo "uploadToDriveResult=$uploadToDriveResult" >> "$GITHUB_OUTPUT"
          echo "uploadToFirebaseResult=$uploadToFirebaseResult" >> "$GITHUB_OUTPUT"
          echo "verName=$verName" >> "$GITHUB_OUTPUT"
          echo "verCode=$verCode" >> "$GITHUB_OUTPUT"
      - name: Notify build on Slack channel
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: ${{ secrets.SLACK_USERNAME }}
          SLACK_ICON: ${{ secrets.SLACK_ICON }}
          SLACK_TITLE: "${{ secrets.APP_NAME }} build is available now!"
          MSG_MINIMAL: true
          SLACK_LINK_NAMES: true
          SLACK_MESSAGE: ":black_small_square: Version: `${{ steps.resultMessage.outputs.verName }} - ${{ steps.resultMessage.outputs.verCode }}`\n:black_small_square: Environment: `dev`\n:black_small_square: Build type: `${{ inputs.buildType }}`\n:black_small_square: Output: `${{ inputs.outputFormat }}` `${{ steps.buildapk.outputs.apk_size }}`\n:black_small_square: Branch: `${{ github.ref_name }}`\n\nRelease notes:\n${{ steps.readReleaseNotes.outputs.release_notes }}\n\nGoogle Drive: ${{ steps.resultMessage.outputs.uploadToDriveResult }}\nFirebase: ${{ steps.resultMessage.outputs.uploadToFirebaseResult }}\n\ncc\n${{ secrets.SLACK_QAS }}"
          SLACK_FOOTER: "Thanks,\nAndroid team"